### ISSUE TITLE
download_catalogue error

### ISSUE THREAD

**Issue by jbagnoli** [ATCC-Bioinformatics/genome_portal_api#20]
Reported by Siva:

I started playing with the API. Thanks for the clear instructions in the documentation. I was able to download data with the function, search_product.
However, when I tried the function, download_catalogue I get the following error. It appears that no data is returned. 

UnboundLocalError                         Traceback (most recent call last) 
test.py in line 1
----> 16 download_catalogue(jwt=jwt,output='catalogue.pkl')

File env/lib/python3.8/site-packages/genome_portal_api/genome_portal_api.py:284, in download_catalogue(**kwargs)
    282 if data == []:
    283   empty_result=True
--> 284   raise emptyResultsError(message)
    285 else:
    286   all_data += data

UnboundLocalError: local variable 'message' referenced before assignment

**Comment by d-yarmosh** [comment]
Was an order of operations issue in the try/except clause of download_catalogue that has been resolved.
