### ISSUE TITLE
Ability to refresh tokens via the API

### ISSUE THREAD

**Issue by knightjdr** [ATCC-Bioinformatics/genome_portal_api#23]
**Is your feature request related to a problem? Please describe.**
Having to manually request a token from the web interface would be okay if they lived for an extended period of time, but 15 minutes is too short.

**Describe the solution you'd like**
Having longer-lived tokens or the ability to refresh them programmatically would be great. Something like `refresh_token("MY_TOKEN")`, or even have a class you can initialize with the token that has the API methods associated with it, and it would then automatically refresh the token for you whenever necessary.

**Comment by jonathanjacobs** [comment]
This is a known limitation put into place by our partner, One Codex, who is hosting the backend. I expect in the next release of the API later this year we will have this feature or something similar implemented.

**Comment by jbagnoli** [comment]
We now use an API key without the time limitation. The README has been updated with the instructions.
