### ISSUE TITLE
download_catalogue only returns 2529 items

### ISSUE THREAD

**Issue by knightjdr** [ATCC-Bioinformatics/genome_portal_api#25]
**Describe the bug**
The download_catalogue function only returns a small portion of the catalog, or is this only the catalog for the genome portal?

**To Reproduce**
```
from genome_portal_api import download_catalogue

jwt = "MY_TOKEN"
catalogue = download_catalogue(jwt=jwt)
print(len(catalogue))
```

**Expected behavior**
I was expecting to download information for ~75000 strains from the full ATCC catalog.

**Comment by jbagnoli** [comment]
Hello,
Currently the API only allows access to the items currently published in the Genome Portal which does not include all of ATCC Products right now.

**Comment by jonathanjacobs** [comment]
full access to metadata from all strains - regardless of whether we have completed sequencing or not - is something I expect we will be adding to the feature set of our next major release in 2023.
