### ISSUE TITLE
Download assembly behavior

### ISSUE THREAD

**Issue by jbagnoli** [ATCC-Bioinformatics/genome_portal_api#26]
I used the API to get data from the ATCC genome portal. First of all, the documentation is very clear. I was able to get started immediately. I used the API mainly to get all the bacterial assemblies and their meta data available in the portal. I first tried download_all_genomes() function. It did not work. I imagine this function was probably deprecated as indicated in the documentation.  Then, I tried getting the assemblies using the assembly id as follows:

1.	Get the catalog using download_catalogue()
2.	With the assembly id from the catalog, get the assembly download link using assembly_download_link()
3.	Use Python Requests library's get() function to download the assembly from the assembly download link. 

I was able to download the assemblies but I ran in to problems when I try to do in bulk. After a couple of successful downloads, the requests.get() function fails with 404 error. I even added pauses (> 5 seconds) between requests.The download links were valid. I was able to download the files from a browser. Have you or colleagues encountered this problem? 

Perhaps, there are other ways to achieve what I am trying to do (to get all assemblies and their meta data). Please let me know if you have any suggestions.

**Comment by josephpetrone** [comment]
Thank you for bringing this to our attention! We recently underwent a large development cycle of the API scripts, and have addressed the issues that causes this behavior in the [V1.0.0](https://github.com/ATCC-Bioinformatics/genome_portal_api/releases/tag/v1.0.0) production release. 

To achieve this now, it is as simple as generating a list of all available genomes and their metadata, and then iterating through that list to download the entire collection using their unique ['id']. Here is a way you should be able to tackle this using list comprehension with the new release.
1. `global_genome_metadata=download_all_genomes()`
3. `[download_assembly(id=item['id'], output='fasta', download_dir="/directory/for/download/") for item in global_genome_metadata]`

This will take time to download all the entire collection, but the fasta files will be uniquely saved based on their taxonomy and ATCC catalog numbers to the download directory you provided. Thank you for using the ATCC Genome Portal API!
